# Generated by Django 4.2.4 on 2023-08-28 22:22

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Material')),
                ('weight', models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Peso en Kilogramos', max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Peso del material')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Precio por Kilogramo', max_digits=10, verbose_name='Precio x Kg')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('status', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiales',
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('weight', models.IntegerField(help_text='Peso en Kilogramos', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)], verbose_name='Cantidad recolectada')),
                ('fecha', models.DateField(help_text='Fecha en que se realizó la recolección', verbose_name='Fecha de recolección')),
                ('hora', models.TimeField(help_text='Hora en que se realizó la recolección', verbose_name='Hora de recolección')),
                ('material', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='collected', to='recycle_one.material')),
            ],
            options={
                'verbose_name': 'Recoleccion',
                'verbose_name_plural': 'Recolecciones',
            },
        ),
    ]
